import {
    UI_VALUE_LOADING_CHECKOUT_ADDRESS,
    UI_VALUE_LOADING_FULFILLMENT,
    UI_VALUE_SHOW_SHOPPING_CART,
    UI_VALUE_EXPEND_SIDEBAR,
} from 'environment'

export const SELECTOR_UI_VALUE = (value: any) => (state: any) => state.uiConfig[value]

export const SELECTOR_UI_LOADING_CHECKOUT_ADDRESS = SELECTOR_UI_VALUE(UI_VALUE_LOADING_CHECKOUT_ADDRESS)

export const SELECTOR_UI_LOADING_FULFILLMENT = SELECTOR_UI_VALUE(UI_VALUE_LOADING_FULFILLMENT)

export const SELECTOR_UI_SHOW_SHOPPING_CART = SELECTOR_UI_VALUE(UI_VALUE_SHOW_SHOPPING_CART)

export const SELECTOR_UI_EXPAND_SIDEBAR = SELECTOR_UI_VALUE(UI_VALUE_EXPEND_SIDEBAR)
